kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipelines-image-builder
  namespace: pipelines-image-registry
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "system:image-builder"
